context:
    links:
      - text: "About"
        url: "#"
      - text: "Services"
        url: "#"
        children:
          - text: "Service 1"
            url: "#"
          - text: "Service 2"
            url: "#"
      - text: "Dearly Design Co."
        url: "#"
        logo: true
      - text: "Shop"
        url: "#"
      - text: "Contact"
        url: "#"
