context:
  links:
    - text: "Skills"
      url: "#skills"
    - text: "Work"
      url: "#work"
    - text: "About"
      url: "#about"
    - text: "Dearly"
      url: "#dearly"
    - text: "Reviews"
      url: "#reviews"
    - text: "Contact Test"
      url: "#contact"
