title: 'Text Block'
context:
  title_fancy: 'Hey!'
  title: 'We&rsquo;re Dearly, and we like to party.'
  content: 'Dearly Design Co. is a husband and wife team inspired by cocktails and confetti and fueled by coffee (and fur-baby cuddles). We provide stationery, paper goods and branding for modern brides, creative events and beautiful businesses.'
