context:
  skills:
    - text: "Print Design"
      machine_name: "print"
    - text: "Branding"
      machine_name: "branding"
    - text: "Web Design"
      machine_name: "web_design"
    - text: "Photo & Video"
      machine_name: "photo_video"
    - text: "Writing"
      machine_name: "writing"
    - text: "Project Management"
      machine_name: "project_management"
