title: Action List
context:
  title: "Bold Design for the Modern Bride"
  items:
    - Save the dates
    - Invitation suites
    - Programs &amp; Menus
    - Day of paper goods
  button:
    content: See More
    href: http://www.google.com
